os:
  - linux
#  - osx
# language: objective-c
language: c++
compiler: gcc
# node_js: '0.10'
env:
  global:
    - secure: kjz286d6rs2VHpv4WnxAOYXcdTIaTaABZ0SNXf27r5H+NDu5qx8ZSeCmj/9op/sDjTtpkLKhi2a0njUCWwak28RAWP3dNkT92MkUPVKBkevznSxWeqwLHoUos3AJnhPMB+cwrWvmRC+Ljt5K1q8SxQsS/HXM9pzKL3DG3qxM+eo=
  matrix:
    - NAME="linux" \
        OF_ROOT="$PWD" \
        SCRIPT="scripts/linux/testTemplate.sh"
    - NAME="android-armv7" \
        SCRIPT_PATH="scripts/android" \
        OF_ROOT="$PWD" \
        SCRIPT="$SCRIPT_PATH/testTemplate.sh armv7"
    - NAME="android-x86" \
        SCRIPT_PATH="scripts/android" \
        OF_ROOT="$PWD" \
        SCRIPT="$SCRIPT_PATH/testTemplate.sh x86"
    - NAME="docs" \
        SCRIPT_PATH="scripts/dev" \
        SCRIPT="$SCRIPT_PATH/documentation.sh"
matrix:
  include:
    # fully specify builds, apparenly include can't dynamically expand matrix entries
    - os: osx
      compiler: clang
      env: NAME="osx" \
          SCRIPT_PATH="scripts/$NAME" \
          SCRIPT="$SCRIPT_PATH/testTemplate.sh"    
    - os: osx
      compiler: clang
      env: NAME="ios" \
          SCRIPT_PATH="scripts/$NAME" \
          SCRIPT="$SCRIPT_PATH/testTemplate.sh"

before_install:
    - "if [ \"$NAME\" == \"docs\" ]; then scripts/dev/documentation.sh before_install; fi"
    - if [ "$NAME" == "linux" ]; then 
        sudo scripts/linux/ubuntu/install_dependencies.sh;
        export CXX=g++-4.9;
      fi
install:
    "if [ \"$NAME\" == \"android-armv7\" ] || [ \"$NAME\" == \"android-x86\" ]; then scripts/android/install_tests_env.sh; fi"
script:
    "$SCRIPT"
after_success:
    "if [ \"$NAME\" == \"docs\" ]; then scripts/dev/documentation.sh after_success; fi"
git:
    depth: 10
#notifications:
#    webhooks: http://192.237.185.151/web-hooks/travis_done.cgi
